export const MAX_GUESS_LENGTH=5;
export const MAX_GUESS_TIMES=6;
export const DEFAULT_NOTIFICATION_DURATION=2000;
export const DEFAULT_NOTIFICATION_ANIMATION_DURATION=300;
export const DEFAULT_CELL_REVEAL_DURATION=1300;
